# Name your project! Project names should contain only lowercase characters
# and underscores. 
name: 'dbt_oracle_d5'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_oracle_d5'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
log-path: "logs"
packages-install-path: "dbt_packages"  # install using : dbt deps
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

sources:  
  dbt_oracle_d5:  
    +enabled: true

# Configuring models
models: 
  dbt_oracle_d5:
    example:
      +enabled: false

    staging: 
      +tags: staging
      +materialized: view

    legacy:
      +enabled: false

    marts:
      +materialized: table
      +on_schema_change: "append_new_columns"
      +meta:
        favorite_color: red
        
      doc:
        +enabled: false

      ldm_fin:
        +tags: ldm_fin

      ldm_fin_out:
        +tags: ldm_fin_out
        +materialized: view

      ldm_sbv:
        +tags: ldm_sbv

      ldm_sbv_out:
        +tags: ldm_sbv_out
        +materialized: view

# on-run-start: "{{ generate_sequences() }}" 
# on-run-end: "{{ generate_sequences() }}" 

vars:    # Global Variables : The variable will be accessible in all resources
         # syntax : {{ var("d_def_value_date_future") }}
  'dbt_date:time_zone'      : 'Asia/Ho_Chi_Minh'
  v_xna                     : 'XNA'
  v_xap                     : 'XAP'
  n_minus_one               : -1
  n_one                     : 1
  n_two                     : 2
  n_three                   : 3
  n_zero                    : 0
  v_code_zero               : '0'
  v_flag_x                  : 'X'
  v_flag_y                  : 'Y'
  v_flag_n                  : 'N'
  v_code_change_type_del    : 'D'
  v_code_active             : 'a'
  v_code_due_status_y       : 'y'
  v_code_due_status_n       : 'n'
  d_def_value_date_hist     : date'1000-01-01'
  d_def_value_date_future   : date'3000-01-01'
  d_high_timestamp          : date'3000-01-01 00:00:00'


dispatch: # inject package
  - macro_namespace: dbt
    search_order: ['dbt_oracle_d5', 'my_snapshot_helpers', 'dbt']