dbt_oracle_d5:
  
  target: dev_d5

  outputs:
    dev_d5:
      type: oracle
      host: DBVN00D5HD.CZ.INFRA
      user: appdeploy
      password: VN00D5HD
      port: 1521
      protocol: tcp
      database: VN00D5HD
      schema: LDM_FIN
      service: VN00D5HD.CZ.INFRA
      threads: 4