/*
  - created by        : chuong.nguyen  - vndm2 
  - created at        : 21-Nov-2023
  - updated at        : 01-Jan-3000
*/

BEGIN
    EXECUTE IMMEDIATE 
      q'[CREATE TABLE LDM_SBV.DBT_FT_ACCOUNTING_ONLINE_NEW_TT
      (	
        SKF_ACCOUNTING_ONLINE     INTEGER           NOT NULL
      , CODE_SOURCE_SYSTEM        VARCHAR2(10)      NOT NULL
      , ID_SOURCE                 VARCHAR2(30)      NOT NULL
      , DATE_EFFECTIVE            DATE              NOT NULL
      , FLAG_DELETED              VARCHAR2(1 CHAR)  NOT NULL
      , DTIME_INSERTED            DATE              NOT NULL
      , DTIME_UPDATED             DATE              NOT NULL
      , SKP_CONTRACT              INTEGER           NOT NULL
      , ID_CONTRACT               NUMBER(38,0)      NOT NULL
      , ID_CLIENT                 NUMBER(38,0)      NOT NULL
      , CODE_MOVE_TYPE            VARCHAR2(50)      NOT NULL
      , TEXT_ACCOUNT_MOVE_DESC    VARCHAR2(255)     NOT NULL
      , AMT_ACCOUNTED_VALUE       NUMBER(18,4)
      , DATE_ACCOUNTED            DATE              NOT NULL
      , DATE_ACCOUNTING_MOVE      DATE              NOT NULL
      , DTIME_ACC_SYSTEM_CREATED  DATE              NOT NULL
      , CODE_TRANSACTION_SUBTYPE  VARCHAR2(256)     NOT NULL
      , CODE_CREDIT_TYPE          VARCHAR2(30)      NOT NULL
      , CODE_OWNER                VARCHAR2(30)      NOT NULL
      , TEXT_CONTRACT_NUMBER      VARCHAR2(255)     NOT NULL
      , DATE_CREATION             DATE              NOT NULL
      , ID_ACCOUNTING_EVENT       NUMBER(38,0)      NOT NULL
      , CODE_CONTRACT_TERM        VARCHAR2(15)      NOT NULL
      , NAME_STATUS_ACQUISITION   VARCHAR2(80)      NOT NULL
      , AMT_ACCOUNTED_VALUE_R     NUMBER(18,4)
      , CONSTRAINT PK_DBT_FT_ACCOUNTING_ONLINE_NEW_TT PRIMARY KEY (SKF_ACCOUNTING_ONLINE)  USING INDEX  TABLESPACE LDM_SBV_IDX 
      )
      TABLESPACE LDM_SBV_DATA 
      PARTITION BY RANGE (DATE_ACCOUNTED)
      INTERVAL( NUMTOYMINTERVAL(1,'MONTH'))
      SUBPARTITION BY LIST (CODE_CREDIT_TYPE) 
      SUBPARTITION TEMPLATE  (
      SUBPARTITION P_COL VALUES ( 'COL' ),
      SUBPARTITION P_CAL VALUES ( 'CAL' ),
      SUBPARTITION P_REV VALUES ( 'REV' ),
      SUBPARTITION PDEF VALUES ( DEFAULT )
      )
      (
      PARTITION p01 values LESS THAN (TO_DATE('01-01-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p02 values LESS THAN (TO_DATE('01-02-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p03 values LESS THAN (TO_DATE('01-03-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p04 values LESS THAN (TO_DATE('01-04-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p05 values LESS THAN (TO_DATE('01-05-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p06 values LESS THAN (TO_DATE('01-06-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p07 values LESS THAN (TO_DATE('01-07-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p08 values LESS THAN (TO_DATE('01-08-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p09 values LESS THAN (TO_DATE('01-09-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p10 values LESS THAN (TO_DATE('01-10-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p11 values LESS THAN (TO_DATE('01-11-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p12 values LESS THAN (TO_DATE('01-12-2023','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA,
      PARTITION p13 values LESS THAN (TO_DATE('01-01-2024','DD-MM-YYYY')) TABLESPACE LDM_SBV_DATA 
      )
      ENABLE ROW MOVEMENT
]';

EXCEPTION
    WHEN OTHERS THEN
        IF (SQLCODE = -955)
        THEN
            Dbms_output.Put_line('Already done, do nothing');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX LDM_SBV.P_DBT_FT_ACCOUNTING_ONLINE_NEW_TT ON LDM_SBV.DBT_FT_ACCOUNTING_ONLINE_NEW_TT
    (SKP_CONTRACT) 
    TABLESPACE LDM_SBV_IDX
';
EXCEPTION
  WHEN OTHERS THEN
    IF (SQLCODE IN (-955, -2261, -2260, -1408))
    THEN
      Dbms_output.Put_line('Already done, do nothing');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX LDM_SBV.UK_DBT_FT_ACCOUNTING_ONLINE_NEW_TT 
    ON LDM_SBV.DBT_FT_ACCOUNTING_ONLINE_NEW_TT
    (ID_SOURCE) 
    TABLESPACE LDM_SBV_IDX
';
EXCEPTION
  WHEN OTHERS THEN
    IF (SQLCODE IN (-955, -2261, -2260, -1408))
    THEN
      Dbms_output.Put_line('Already done, do nothing');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
    ALTER TABLE LDM_SBV.DBT_FT_ACCOUNTING_ONLINE_NEW_TT 
        ADD CONSTRAINT UK_DBT_FT_ACCOUNTING_ONLINE_NEW_TT 
        UNIQUE (ID_SOURCE)
        USING INDEX TABLESPACE LDM_SBV_IDX';
EXCEPTION
    WHEN OTHERS THEN
        IF (SQLCODE IN (-955, -2261, -2260))
        THEN
            Dbms_output.Put_line('Already done, do nothing');
        ELSE
            RAISE;
        END IF;
END;
/