version: 2

sources: 
  - name: bq_source # source_name
    config:
      enabled: true
    database: learn-dbt-397522 # BQ project Name
    schema: dbt_bigquery # BQ dataset

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: loaded_at

    tables:
      - name: tiny_t
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
        loaded_at_field: updated_at

      - name: tiny_t_2
        freshness: null # do not check freshness for this table
        
# insert new row
# insert into `learn-dbt-397522.dbt_bigquery.tiny_t` ( id,status,updated_at) values (4,'completed', current_timestamp );