version: 2

sources: 

  - name: ldm_sbv
    config:
      enabled: true
    schema: ldm_sbv
    tables:
      - name: clt_adld_newband

  - name: owner_int
    config:
      enabled: true
    schema: owner_int
    tables:
      - name: in_hom_client # view/table have to granted to ldm_fin/ldm_sbv in advance
