version: 2

sources: 
  - name: ldm_fin_source
    config:
      enabled: true
    schema: ldm_fin  # by default schema = source name 

    tables:
      - name: clt_bi_pcs_payment_channel
        # freshness:
        #   warn_after: {count: 6, period: hour}
        #   error_after: {count: 12, period: hour}
        # loaded_at_field: updated_at
