version: 2

sources: 
  - name: owner_int
    config:
      enabled: true
    schema: owner_int
    tables:
      - name: in_hom_client # view/table have to granted to ldm_fin/ldm_sbv in advance
      - name: in_hom_product 
      - name: in_bkng_rank_001
      - name: in_bkng_movement_002
      - name: in_csd_enum_value

  - name: sbv_owner_int
    config:
      enabled: true
    schema: ldm_sbv
    tables:
      - name: in_hom_product 


